permissions:
  contents: write

name: Auto Semantic Release

on:
  workflow_dispatch:

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
          echo "Latest tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump tag version
        id: bump_tag
        run: |
          LAST_TAG="${{ steps.get_tag.outputs.tag }}"
          STRIPPED=$(echo "$LAST_TAG" | sed 's/^v//')
          IFS='.' read -r major minor patch <<<"$STRIPPED"
          NEW_PATCH=$((patch + 1))
          NEW_TAG="v$major.$minor.$NEW_PATCH"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}
